In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/tannguyen/Documents/CODE/DIM_SHOPEE_DISHES_comma.csv')
df

/var/folders/hl/66744hx91bg6k35x2s20h9780000gn/T/ipykernel_1333/1992518476.py:1: DtypeWarning: Columns (4,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/tannguyen/Documents/CODE/DIM_SHOPEE_DISHES_comma.csv')

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
0,2635001,160.0,Món Hot,-11.0,NaN,NaN,1114911.0,46050027.0,Trà Đào,NaN,1,Trà đào kèm miếng đào tươi,4.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
1,2635001,136.0,Món Hot,-11.0,NaN,NaN,1114911.0,28885958.0,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126.0,Món Hot,-11.0,NaN,NaN,1114911.0,46050017.0,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121626885.0,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0.0,0.0,NaN,0,29000.0,1,"{""has_alcohol"": false}",NaN
4,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121637344.0,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163.0,Menu,0.0,NaN,NaN,887857.0,7315384.0,Hoành thánh chiên,NaN,1,NaN,1.0,0.0,NaN,0,28000.0,1,"{""has_alcohol"": false}",NaN
1867751,671292,151.0,Menu,0.0,NaN,NaN,887857.0,7315403.0,Thanh cua cuốn,NaN,1,NaN,4.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867752,671292,115.0,Menu,0.0,NaN,NaN,887857.0,7315433.0,Bánh bao thịt,NaN,1,NaN,3.0,0.0,NaN,0,27000.0,1,"{""has_alcohol"": false}",NaN
1867753,671292,93.0,Menu,0.0,NaN,NaN,887857.0,7315413.0,Bắp,NaN,1,NaN,3.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867754,671292,48.0,Menu,0.0,NaN,NaN,887857.0,7315398.0,Thanh cua,NaN,1,NaN,1.0,0.0,NaN,0,32000.0,1,"{""has_alcohol"": false}",NaN

In [10]:
df_null = df[df['restaurant_id']>70000]
df_null

,restaurant_id,restaurant_url,restaurant_name,name_en,restaurant_short_description,address_detail,address_district,address_city,address_full,lat,...,checked_in_count,favourite_count,review_average_count,review_bad_count,review_count,review_excellent_count,review_good_count,view_count,wanted_count,picture_count
0,786442,lien-hoa-ga-ac-oc-heo-tiem-thuoc-bac,Liên Hoa - Gà Ác & Óc Heo Tiềm Thuốc Bắc,NaN,NaN,"582 Quốc Lộ 13, P. Hiệp Bình Phước",Thủ Đức,TP. HCM,"582 Quốc Lộ 13, P. Hiệp Bình Phước, Thủ Đức, T...",10.850111,...,0,1,NaN,NaN,0.0,NaN,NaN,230.0,0.0,0.0
3,786494,bun-mi-vang-hu-tieu-mi-thap-cam,Bún Mì Vàng & Hủ Tiếu Mì Thập Cẩm,NaN,NaN,"89 Trần Quý, P. 4",Quận 11,TP. HCM,"89 Trần Quý, P. 4, Quận 11, TP. HCM",10.758493,...,0,7,1.0,0.0,2.0,0.0,1.0,443.0,2.0,12.0
5,786523,sinh-to-minh-thien-le-van-luong,Sinh Tố Minh Thiên - Lê Văn Lương,NaN,NaN,"595 Lê Văn Lương, P. Tân Phong",Quận 7,TP. HCM,"595 Lê Văn Lương, P. Tân Phong, Quận 7, TP. HCM",10.732550,...,0,0,NaN,NaN,0.0,NaN,NaN,71.0,0.0,3.0
6,786524,hexagon-coffee-nguyen-van-qua,Hexagon Coffee - Nguyễn Văn Quá,NaN,NaN,"92 Nguyễn Văn Quá, P. Đông Hưng Thuận",Quận 12,TP. HCM,"92 Nguyễn Văn Quá, P. Đông Hưng Thuận, Quận 12...",10.828559,...,0,0,NaN,NaN,0.0,NaN,NaN,45.0,0.0,1.0
7,786530,pho-nam-dinh-368-nguyen-van-qua,Phở Nam Định - 368 Nguyễn Văn Quá,NaN,NaN,"368 Nguyễn Văn Quá, P. Đông Hưng Thuận",Quận 12,TP. HCM,"368 Nguyễn Văn Quá, P. Đông Hưng Thuận, Quận 1...",10.836282,...,0,0,NaN,NaN,0.0,NaN,NaN,77.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61569,1083136,vu-heo-nuong-family-bbq,Vú Heo Nướng - Family BBQ,NaN,NaN,"219/66 Dương Bá Trạc, P. 1",Quận 8,TP. HCM,"219/66 Dương Bá Trạc, P. 1, Quận 8, TP. HCM",10.746812,...,0,0,NaN,NaN,0.0,NaN,NaN,74.0,0.0,0.0
61570,1000033541,banh-canh-cua-tra-sua-thanh-tam-banh-canh-cua-...,Bánh Canh Cua Trà Sữa Thanh Tâm - Bánh Canh Cu...,NaN,NaN,"231E/40 Dương Bá Trạc, P. 1",Quận 8,TP. HCM,"231E/40 Dương Bá Trạc, P. 1, Quận 8, TP. HCM",10.747212,...,0,0,NaN,NaN,0.0,NaN,NaN,27.0,0.0,0.0
61571,645072,van-ngoc-com-ga-xoi-mo,Vân Ngọc - Cơm Gà Xối Mỡ,NaN,NaN,"13 Bành Văn Trân, P. 7",Tân Bình,TP. HCM,"13 Bành Văn Trân, P. 7, Tân Bình, TP. HCM",10.789352,...,0,8,0.0,0.0,3.0,1.0,2.0,825.0,9.0,20.0
61572,708242,passio-coffee-nguyen-thai-binh,Passio Coffee - 279 Nguyễn Thái Bình,NaN,NaN,279 Nguyễn Thái Bình,Tân Bình,TP. HCM,"279 Nguyễn Thái Bình, Tân Bình, TP. HCM",10.796930,...,2,2,1.0,2.0,8.0,0.0,5.0,2343.0,1.0,49.0
61573,1123133,phuc-long-d1-1-nguyen-thi-tu,Phúc Long D1/1 Nguyễn Thị Tú,NaN,NaN,"D1/1 Nguyễn Thị Tú, Ấp 4, Xã Vĩnh Lộc B",Bình Chánh,TP. HCM,"D1/1 Nguyễn Thị Tú, Ấp 4, Xã Vĩnh Lộc B, Bình ...",10.814677,...,0,0,NaN,NaN,0.0,NaN,NaN,21.0,0.0,0.0

In [7]:
duplicates = df[df.duplicated(subset="dish_restaurant_id")]
duplicates

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
1,2635001,136.0,Món Hot,-11.0,NaN,NaN,1114911.0,28885958.0,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126.0,Món Hot,-11.0,NaN,NaN,1114911.0,46050017.0,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121626885.0,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0.0,0.0,NaN,0,29000.0,1,"{""has_alcohol"": false}",NaN
4,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121637344.0,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
5,2635001,2.0,Món Hot,-11.0,NaN,NaN,1114911.0,121638144.0,Cà Phê Sữa Tươi,NaN,1,NaN,0.0,0.0,NaN,0,25000.0,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163.0,Menu,0.0,NaN,NaN,887857.0,7315384.0,Hoành thánh chiên,NaN,1,NaN,1.0,0.0,NaN,0,28000.0,1,"{""has_alcohol"": false}",NaN
1867751,671292,151.0,Menu,0.0,NaN,NaN,887857.0,7315403.0,Thanh cua cuốn,NaN,1,NaN,4.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867752,671292,115.0,Menu,0.0,NaN,NaN,887857.0,7315433.0,Bánh bao thịt,NaN,1,NaN,3.0,0.0,NaN,0,27000.0,1,"{""has_alcohol"": false}",NaN
1867753,671292,93.0,Menu,0.0,NaN,NaN,887857.0,7315413.0,Bắp,NaN,1,NaN,3.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867754,671292,48.0,Menu,0.0,NaN,NaN,887857.0,7315398.0,Thanh cua,NaN,1,NaN,1.0,0.0,NaN,0,32000.0,1,"{""has_alcohol"": false}",NaN

In [8]:
df_check = df[df['dish_restaurant_id'].isnull()]
df_check

Empty DataFrame
Columns: [catalog_id, dish_total_order, catalog_name, catalog_rank, catalog_partner_catalog_id, catalog_description, dish_restaurant_id, dish_id, dish_name, dish_partner_dish_id, dish_listing_status, dish_description, dish_total_like, dish_rank, dish_picture_label, dish_is_hidden, dish_price, dish_is_group_discount_item, dishes_property_info, url]
Index: []

In [21]:
dish_restaurant_ids = df['dish_restaurant_id']
non_numeric_ids = []
for id_value in dish_restaurant_ids:
    if not pd.isnull(id_value) and not isinstance(id_value, (int, float)):
        non_numeric_ids.append(id_value)

print(non_numeric_ids)

['Nga']

In [18]:
df['dish_restaurant_id'].loc[2008] = 'Nga'df['dish_restaurant_id'].loc[2008] = 'Nga'

1141761.0

In [22]:
df['dish_restaurant_id'].loc[2008] = 1141761.0

In [23]:
df['dish_restaurant_id'].loc[2008]

1141761.0

In [24]:
df

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
0,2635001,160.0,Món Hot,-11.0,NaN,NaN,1114911.0,46050027.0,Trà Đào,NaN,1,Trà đào kèm miếng đào tươi,4.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
1,2635001,136.0,Món Hot,-11.0,NaN,NaN,1114911.0,28885958.0,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126.0,Món Hot,-11.0,NaN,NaN,1114911.0,46050017.0,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3.0,0.0,NaN,0,24000.0,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121626885.0,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0.0,0.0,NaN,0,29000.0,1,"{""has_alcohol"": false}",NaN
4,2635001,4.0,Món Hot,-11.0,NaN,NaN,1114911.0,121637344.0,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163.0,Menu,0.0,NaN,NaN,887857.0,7315384.0,Hoành thánh chiên,NaN,1,NaN,1.0,0.0,NaN,0,28000.0,1,"{""has_alcohol"": false}",NaN
1867751,671292,151.0,Menu,0.0,NaN,NaN,887857.0,7315403.0,Thanh cua cuốn,NaN,1,NaN,4.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867752,671292,115.0,Menu,0.0,NaN,NaN,887857.0,7315433.0,Bánh bao thịt,NaN,1,NaN,3.0,0.0,NaN,0,27000.0,1,"{""has_alcohol"": false}",NaN
1867753,671292,93.0,Menu,0.0,NaN,NaN,887857.0,7315413.0,Bắp,NaN,1,NaN,3.0,0.0,NaN,0,35000.0,1,"{""has_alcohol"": false}",NaN
1867754,671292,48.0,Menu,0.0,NaN,NaN,887857.0,7315398.0,Thanh cua,NaN,1,NaN,1.0,0.0,NaN,0,32000.0,1,"{""has_alcohol"": false}",NaN

In [26]:
#set integer
df['catalog_id']=df['catalog_id'].astype(int)
df['dish_total_order']=df['dish_total_order'].astype(int)
df['catalog_rank']=df['catalog_rank'].astype(int)
df['dish_restaurant_id']=df['dish_restaurant_id'].astype(int)
df['dish_id']=df['dish_id'].astype(int)
df['dish_total_like']=df['dish_total_like'].astype(int)
df['dish_rank']=df['dish_rank'].astype(int)
df['dish_price']=df['dish_price'].astype(int)

In [27]:
df

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
0,2635001,160,Món Hot,-11,NaN,NaN,1114911,46050027,Trà Đào,NaN,1,Trà đào kèm miếng đào tươi,4,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
1,2635001,136,Món Hot,-11,NaN,NaN,1114911,28885958,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126,Món Hot,-11,NaN,NaN,1114911,46050017,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4,Món Hot,-11,NaN,NaN,1114911,121626885,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0,0,NaN,0,29000,1,"{""has_alcohol"": false}",NaN
4,2635001,4,Món Hot,-11,NaN,NaN,1114911,121637344,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163,Menu,0,NaN,NaN,887857,7315384,Hoành thánh chiên,NaN,1,NaN,1,0,NaN,0,28000,1,"{""has_alcohol"": false}",NaN
1867751,671292,151,Menu,0,NaN,NaN,887857,7315403,Thanh cua cuốn,NaN,1,NaN,4,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867752,671292,115,Menu,0,NaN,NaN,887857,7315433,Bánh bao thịt,NaN,1,NaN,3,0,NaN,0,27000,1,"{""has_alcohol"": false}",NaN
1867753,671292,93,Menu,0,NaN,NaN,887857,7315413,Bắp,NaN,1,NaN,3,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867754,671292,48,Menu,0,NaN,NaN,887857,7315398,Thanh cua,NaN,1,NaN,1,0,NaN,0,32000,1,"{""has_alcohol"": false}",NaN

In [47]:
## clear comma
contain_comma = df['url'].str.contains(',')
comma_cells = df[contain_comma]
comma_cells

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [43]:
df['dish_description'] = df['dish_description'].str.replace(',', ';')

In [52]:
#checking nominate if contain comma in all columns
contains_comma = df.apply(lambda x: x.astype(str).str.contains(','), axis=1).any(axis=1)

comma_rows = df[contains_comma]

print(comma_rows)

Empty DataFrame
Columns: [catalog_id, dish_total_order, catalog_name, catalog_rank, catalog_partner_catalog_id, catalog_description, dish_restaurant_id, dish_id, dish_name, dish_partner_dish_id, dish_listing_status, dish_description, dish_total_like, dish_rank, dish_picture_label, dish_is_hidden, dish_price, dish_is_group_discount_item, dishes_property_info, url]
Index: []

In [48]:
df['url'].iloc[2787]

'https://images.foody.vn/res/g1/1366/s1242x1242/foody-bun cha ca, ca dam, sua-635791347413356544.jpg'

In [49]:
df = df.drop(2787)

In [50]:
df = df.drop(109528)

In [51]:
df

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
0,2635001,160,Món Hot,-11,NaN,NaN,1114911,46050027,Trà Đào,NaN,1,Trà đào kèm miếng đào tươi,4,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
1,2635001,136,Món Hot,-11,NaN,NaN,1114911,28885958,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126,Món Hot,-11,NaN,NaN,1114911,46050017,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4,Món Hot,-11,NaN,NaN,1114911,121626885,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0,0,NaN,0,29000,1,"{""has_alcohol"": false}",NaN
4,2635001,4,Món Hot,-11,NaN,NaN,1114911,121637344,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163,Menu,0,NaN,NaN,887857,7315384,Hoành thánh chiên,NaN,1,NaN,1,0,NaN,0,28000,1,"{""has_alcohol"": false}",NaN
1867751,671292,151,Menu,0,NaN,NaN,887857,7315403,Thanh cua cuốn,NaN,1,NaN,4,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867752,671292,115,Menu,0,NaN,NaN,887857,7315433,Bánh bao thịt,NaN,1,NaN,3,0,NaN,0,27000,1,"{""has_alcohol"": false}",NaN
1867753,671292,93,Menu,0,NaN,NaN,887857,7315413,Bắp,NaN,1,NaN,3,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867754,671292,48,Menu,0,NaN,NaN,887857,7315398,Thanh cua,NaN,1,NaN,1,0,NaN,0,32000,1,"{""has_alcohol"": false}",NaN

In [54]:
pd.to_csv('DIM_SHOPEE_DISHES_commaclean')

AttributeError: module 'pandas' has no attribute 'to_csv'

In [57]:
df.to_csv('DIM_SHOPEE_DISHES_commaclean',index=False)

In [56]:
df

,catalog_id,dish_total_order,catalog_name,catalog_rank,catalog_partner_catalog_id,catalog_description,dish_restaurant_id,dish_id,dish_name,dish_partner_dish_id,dish_listing_status,dish_description,dish_total_like,dish_rank,dish_picture_label,dish_is_hidden,dish_price,dish_is_group_discount_item,dishes_property_info,url
0,2635001,160,Món Hot,-11,NaN,NaN,1114911,46050027,Trà Đào,NaN,1,Trà đào kèm miếng đào tươi,4,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
1,2635001,136,Món Hot,-11,NaN,NaN,1114911,28885958,Trà Sữa Nọng Xanh,NaN,1,Trà Sữa Nọng Xanh là trà sữa vị thái xanh đã b...,55,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g103/1025330/s1242...
2,2635001,126,Món Hot,-11,NaN,NaN,1114911,46050017,Trà Vải,NaN,1,Trà vải tươi mát kèm trái vải,3,0,NaN,0,24000,1,"{""has_alcohol"": false}",https://images.foody.vn/res/g112/1114911/s1242...
3,2635001,4,Món Hot,-11,NaN,NaN,1114911,121626885,Cà Phê Sữa Tươi Hạnh Nhân Phin Di,NaN,1,NaN,0,0,NaN,0,29000,1,"{""has_alcohol"": false}",NaN
4,2635001,4,Món Hot,-11,NaN,NaN,1114911,121637344,Sữa Tươi Trân Châu Đường Đen HQ,NaN,1,NaN,0,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867750,671292,163,Menu,0,NaN,NaN,887857,7315384,Hoành thánh chiên,NaN,1,NaN,1,0,NaN,0,28000,1,"{""has_alcohol"": false}",NaN
1867751,671292,151,Menu,0,NaN,NaN,887857,7315403,Thanh cua cuốn,NaN,1,NaN,4,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867752,671292,115,Menu,0,NaN,NaN,887857,7315433,Bánh bao thịt,NaN,1,NaN,3,0,NaN,0,27000,1,"{""has_alcohol"": false}",NaN
1867753,671292,93,Menu,0,NaN,NaN,887857,7315413,Bắp,NaN,1,NaN,3,0,NaN,0,35000,1,"{""has_alcohol"": false}",NaN
1867754,671292,48,Menu,0,NaN,NaN,887857,7315398,Thanh cua,NaN,1,NaN,1,0,NaN,0,32000,1,"{""has_alcohol"": false}",NaN